export const BOQ_CATEGORIES = [
  "Lighting",
  "Power",
  "Distribution Board",
  "MDB",
  "SMDB",
  "MCC",
  "Cable",
  "Cable Tray",
  "Cable Ladder",
  "Conduit",
  "Earthing",
  "Lightning Protection",
  "Generator",
  "ATS",
  "AMF",
  "UPS",
  "Transformer",
  "Capacitor Bank",
  "Motor",
  "Fire Alarm",
  "CCTV",
  "Data",
  "Access Control",
  "BMS",
  "KNX",
  "DALI",
  "Solar",
  "Miscellaneous",
] as const;

export const DOCUMENT_FOLDERS = [
  "01 Contract",
  "02 BOQ",
  "03 Quotations",
  "04 Drawings",
  "05 Material Submittals",
  "06 Method Statements",
  "07 Risk Assessments",
  "08 Inspection Requests",
  "09 Testing",
  "10 Commissioning",
  "11 Invoices",
  "12 Payments",
  "13 Completion Documents",
  "14 As-Built",
] as const;

export const DRAWING_TYPES = [
  "SLD",
  "Lighting layout",
  "Power layout",
  "DB schedule",
  "Panel schematic",
  "Control diagram",
  "Earthing layout",
  "Lightning protection",
  "Cable schedule",
  "As-built drawing",
] as const;

export const TEST_TEMPLATES: Record<string, string[]> = {
  Cable: [
    "Visual inspection",
    "Continuity",
    "Insulation resistance",
    "Phase identification",
    "Phase sequence",
    "Termination inspection",
    "Torque verification",
  ],
  "DB / Panel": [
    "Visual inspection",
    "Labeling",
    "Tightness",
    "Insulation resistance",
    "Earth continuity",
    "RCD test",
    "Functional test",
  ],
  Earthing: ["Earth resistance", "Earth continuity", "Bonding", "Visual inspection"],
  Lighting: [
    "Functional test",
    "Lux measurement",
    "Emergency lighting test",
    "Sensor test",
    "Control test",
  ],
  Generator: [
    "Visual inspection",
    "Battery",
    "Fuel",
    "Oil",
    "ATS",
    "AMF",
    "Manual mode",
    "Auto mode",
    "Load test",
  ],
  Motor: [
    "Insulation resistance",
    "Continuity",
    "Rotation",
    "Phase sequence",
    "Protection",
    "No-load test",
    "Load test",
  ],
  UPS: [
    "Input voltage",
    "Output voltage",
    "Battery",
    "Bypass",
    "Alarm",
    "Load test",
    "Runtime",
  ],
};

export const UNITS = ["Nos", "m", "m²", "m³", "kg", "lot", "set", "core", "point"] as const;

export const STANDARD_CATEGORIES = [
  "Nepal Electrical standards",
  "Building regulations",
  "IEC",
  "NEC",
  "IEEE",
  "Manufacturer manuals",
  "Project specifications",
] as const;

export const SERVICES = [
  { slug: "electrical-contracting", title: "Electrical Contracting", body: "End-to-end electrical contracting for new-build and retrofit projects across Nepal." },
  { slug: "industrial-electrical", title: "Industrial Electrical", body: "Factory power distribution, MCC, motors, and process electrical packages." },
  { slug: "building-electrical", title: "Building Electrical", body: "Lighting, power, ELV and life-safety systems for commercial and residential buildings." },
  { slug: "panel-installation", title: "Panel Installation", body: "MDB, SMDB, DB and control panel supply, assembly, installation and commissioning." },
  { slug: "generator-ats", title: "Generator & ATS", body: "Standby generation, ATS/AMF, fuel systems and load testing." },
  { slug: "ups", title: "UPS", body: "Critical power, battery systems and runtime design for hospitals, data and hotels." },
  { slug: "solar", title: "Solar", body: "On-grid and hybrid PV with protection, earthing and utility interface." },
  { slug: "earthing", title: "Earthing", body: "Earthing grids, bonding and earth resistance testing." },
  { slug: "lightning-protection", title: "Lightning Protection", body: "Air termination, down conductors and surge protection." },
  { slug: "fire-alarm", title: "Fire Alarm", body: "Addressable and conventional fire detection, voice alarm and interfacing." },
  { slug: "cctv", title: "CCTV", body: "IP CCTV, recording and viewing for sites and occupied buildings." },
  { slug: "bms", title: "BMS", body: "Building management, metering and plant monitoring." },
  { slug: "automation", title: "Automation", body: "KNX, DALI, motor control and industrial automation support." },
  { slug: "testing-commissioning", title: "Testing & Commissioning", body: "Inspection, testing and commissioning with documented reports." },
  { slug: "maintenance", title: "Maintenance", body: "Preventive maintenance, breakdown response and warranty support." },
];
