import type { Role } from "@prisma/client";
import {
  LayoutDashboard,
  FolderKanban,
  Users,
  ClipboardList,
  FileSpreadsheet,
  Receipt,
  Boxes,
  Truck,
  HardHat,
  Calculator,
  PenTool,
  FileText,
  FlaskConical,
  Wallet,
  Banknote,
  PieChart,
  Files,
  Settings,
  UserCog,
  Wrench,
  BookOpen,
  ShoppingCart,
  Warehouse,
  MapPinned,
} from "lucide-react";

export const APP_NAV = [
  { href: "/dashboard", label: "Dashboard", icon: LayoutDashboard, module: "dashboard" },
  { href: "/projects", label: "Projects", icon: FolderKanban, module: "projects" },
  { href: "/clients", label: "Clients", icon: Users, module: "clients" },
  { href: "/boq", label: "BOQ", icon: ClipboardList, module: "boq" },
  { href: "/quotations", label: "Quotations", icon: FileSpreadsheet, module: "quotations" },
  { href: "/invoices", label: "Invoices", icon: Receipt, module: "invoices" },
  { href: "/materials", label: "Materials", icon: Boxes, module: "materials" },
  { href: "/suppliers", label: "Suppliers", icon: Truck, module: "suppliers" },
  { href: "/labour", label: "Labour", icon: HardHat, module: "labour" },
  { href: "/costing", label: "Costing", icon: Calculator, module: "costing" },
  { href: "/drawings", label: "Drawings", icon: PenTool, module: "drawings" },
  { href: "/method-statements", label: "Method Statements", icon: FileText, module: "method-statements" },
  { href: "/testing-commissioning", label: "Testing & Cx", icon: FlaskConical, module: "testing-commissioning" },
  { href: "/surveys", label: "Site Surveys", icon: MapPinned, module: "surveys" },
  { href: "/procurement", label: "Procurement", icon: ShoppingCart, module: "procurement" },
  { href: "/inventory", label: "Inventory", icon: Warehouse, module: "inventory" },
  { href: "/expenses", label: "Expenses", icon: Wallet, module: "expenses" },
  { href: "/payments", label: "Payments", icon: Banknote, module: "payments" },
  { href: "/reports", label: "Reports", icon: PieChart, module: "reports" },
  { href: "/documents", label: "Documents", icon: Files, module: "documents" },
  { href: "/tools", label: "Engineering Tools", icon: Wrench, module: "tools" },
  { href: "/standards", label: "Standards", icon: BookOpen, module: "standards" },
  { href: "/users", label: "Users", icon: UserCog, module: "users" },
  { href: "/settings", label: "Settings", icon: Settings, module: "settings" },
] as const;

export const PUBLIC_NAV = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/services", label: "Services" },
  { href: "/work", label: "Projects" },
  { href: "/industries", label: "Industries" },
  { href: "/team", label: "Our Team" },
  { href: "/certifications", label: "Certifications" },
  { href: "/contact", label: "Contact" },
] as const;

export type NavRole = Role;
